// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABO2LAGumEtX2pqaZIcvaJSaEIfqCtjn0',
    appId: '1:850211718490:web:24d93da52fffbf490b5f63',
    messagingSenderId: '850211718490',
    projectId: 'mts-dentaire',
    authDomain: 'mts-dentaire.firebaseapp.com',
    storageBucket: 'mts-dentaire.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyJfj0-QAWgUDZOKaESrveNGNYHZBnaMs',
    appId: '1:850211718490:android:552fd1842e1e71400b5f63',
    messagingSenderId: '850211718490',
    projectId: 'mts-dentaire',
    storageBucket: 'mts-dentaire.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeMm9UT37JAysTk6hXyVsJtd2e0iEe1GI',
    appId: '1:850211718490:ios:3056de220618fdab0b5f63',
    messagingSenderId: '850211718490',
    projectId: 'mts-dentaire',
    storageBucket: 'mts-dentaire.firebasestorage.app',
    iosBundleId: 'com.example.mtsMedicoAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeMm9UT37JAysTk6hXyVsJtd2e0iEe1GI',
    appId: '1:850211718490:ios:3056de220618fdab0b5f63',
    messagingSenderId: '850211718490',
    projectId: 'mts-dentaire',
    storageBucket: 'mts-dentaire.firebasestorage.app',
    iosBundleId: 'com.example.mtsMedicoAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABO2LAGumEtX2pqaZIcvaJSaEIfqCtjn0',
    appId: '1:850211718490:web:5b6a26c393a86b930b5f63',
    messagingSenderId: '850211718490',
    projectId: 'mts-dentaire',
    authDomain: 'mts-dentaire.firebaseapp.com',
    storageBucket: 'mts-dentaire.firebasestorage.app',
  );
}
